app_taipei_mayor/urls.py
from django.urls import path
from . import views  # Import the views module from the current package
# from app_taipei_mayor import views

app_name = 'app_taipei_mayor'

urlpatterns = [
    path('', views.home, name='home'),
    path('api_get_taipei_mayor_data/', views.api_get_taipei_mayor_data),
]

app_top_keyword/urls.py
from django.urls import path
from . import views

app_name = 'app_top_keyword'

urlpatterns = [
    # 會呼叫 views.py 中的 index 方法
    path('', views.home, name='home'),
    path('api_get_cate_topword/', views.api_get_cate_topword, name='api_cate_topword')
]

app_top_voice/urls.py
from django.urls import path
from . import views

app_name = 'app_top_voice'

urlpatterns = [
    path('', views.home, name='home'),
    path('api_cate_topvoice/', views.api_cate_topvoice, name='api_cate_topvoice'),
    path('api_news_volume_data/', views.api_news_volume_data,
         name='api_news_volume_data'),  # 👈 加這行
]

app_user_keyword/urls.py
from django.urls import path
from . import views

app_name = "app_user_keyword"

urlpatterns = [

    path('', views.home, name='home'),
    path('api_get_top_userkey/', views.api_get_top_userkey),

]

line_today/urls.py
from django.urls import path
from . import views

app_name = 'line_today'

urlpatterns = [
    path('movie/', views.movie_home, name='movie_home'),
    path('api/test_movie_titles/', views.test_movie_titles,
         name='test_movie_titles'),
]

website_configs/urls.py
from django.contrib import admin
from django.urls import include
from django.urls import path
from website_configs import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    #  path('admin/', admin.site.urls), 用來管理資料庫的，課堂上沒有交到
    # 訪問 http://127.0.0.1:8000/ 僅可顯示初始網頁
    path('', views.index, name='index'),
    path('top_keyword/', include('app_top_keyword.urls')),
    path('top_person/', include('app_top_person.urls')),
    path('user_keyword/', include('app_user_keyword.urls')),
    path('top_voice/', include('app_top_voice.urls')),
    path('criminal_information/', include('app_Criminal_Information.urls')),
    path('userkeyword_assoc/', include('app_user_keyword_association.urls')),
    path('userkeyword_senti/', include('app_user_keyword_sentiment.urls')),
    path('taipei_mayor/', include('app_taipei_mayor.urls')),
    # full text search and associated keyword display using db
    path('userkeyword_db/', include('app_user_keyword_db.urls')),




    # full text search and associated keyword display using db
    path('topperson_db/', include(('app_top_person_db.urls'))),

    # admin 後台資料庫管理
    path('admin/', admin.site.urls),



    path('line_today/', include(('line_today.urls',
         'line_today'), namespace='line_today')),

]
# 讓開發期間可以讀取媒體檔案
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="zh-TW">
  <head>
    <title>
      {% block title %}
        輿情分析平台
      {% endblock %}
    </title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <!-- Bootstrap 5 CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" />
    {% block extra_css %}

    {% endblock %}
  </head>
  <body>
    <div class="container">
      <div class="row">
        <!-- Navigation Bar -->
        <div class="col-lg-12 mb-2 mt-2">
          <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #e3f2fd">
            <div class="container-fluid">
              <a class="navbar-brand" href="/">輿情大數據</a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>

              <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                  <!-- 基礎熱門分析 -->
                  <div class="btn-group">
                    <button type="button" class="btn dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">熱門分析</button>
                    <div class="dropdown-menu">
                      <a class="dropdown-item" href="{% url 'app_top_keyword:home' %}">熱門關鍵詞分析</a>
                      <a class="dropdown-item" href="{% url 'app_top_person:home' %}">熱門人物分析</a>

                      <a class="dropdown-item" href="#">命名實體熱門分析</a>
                      <a class="dropdown-item" href="#" style="color: green">昨日誰最大</a>
                    </div>
                  </div>

                  <!-- 進階自訂分析 -->
                  <div class="btn-group">
                    <button type="button" class="btn dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">進階查詢</button>
                    <div class="dropdown-menu">
                      <a class="dropdown-item" href="{% url 'app_user_keyword:home' %}">自訂關鍵詞熱門度分析</a>
                      <a class="nav-link" href="{% url 'app_user_keyword_association:home' %}">全文檢索與關聯新聞分析</a>
                      <a class="dropdown-item" href="{% url 'app_user_keyword_sentiment:home' %}">自訂關鍵詞之情緒分析</a>
                    </div>
                  </div>

                  <!-- 特色分析 -->
                  <div class="btn-group">
                    <button type="button" class="btn dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">特色分析</button>
                    <div class="dropdown-menu">
                      <a class="nav-link" href="{% url 'app_top_voice:home' %}" style="color: green">XXX聲量我最大</a>
                      <div class="dropdown-divider"></div>
                      <a class="nav-link" href="{% url 'app_taipei_mayor:home' %}" style="color: green">全球聲量觀測站</a>
                      <div class="dropdown-divider"></div>
                      <a class="nav-link" href="#">政黨聲量排行榜</a>
                      <a class="nav-link" href="#">政治人物聲量排行榜</a>
                      <div class="dropdown-divider"></div>

                      <a class="nav-link" href="#" style="color: green">事件人物聲量相關分析</a>
                    </div>
                  </div>

                  <!-- 新聞推薦系統 -->
                  <div class="btn-group">
                    <button type="button" class="btn dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">新聞推薦系統</button>
                    <div class="dropdown-menu">
                      <a class="dropdown-item" href="#">Bert/Qwen新聞推薦-新聞查找相似新聞</a>
                    </div>
                  </div>

                  <!-- NLP應用 -->
                  <div class="btn-group">
                    <button type="button" class="btn dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">自然語言理解</button>
                    <div class="dropdown-menu">
                      <a class="dropdown-item" href="#">語言模型Bert/Qwen情緒分類</a>
                      <a class="dropdown-item" href="#">語言模型Bert/Qwen新聞分類</a>
                    </div>
                  </div>

                  <!-- 使用資料庫 -->
                  <div class="btn-group">
                    <button type="button" class="btn dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">使用DB</button>
                    <div class="dropdown-menu">
                      <a class="dropdown-item" href="{% url 'app_user_keyword_db:home' %}">自訂全文檢索與關聯分析db</a>

                      <a class="dropdown-item" href="{% url 'app_top_person_db:home' %}">熱門人物(從資料庫查詢)</a>
                      <a class="dropdown-item" href="{% url 'app_top_person_db:calculate_top_person' %}">熱門人物立刻計算(管理者定時執行)</a>
                    </div>
                  </div>

                  <!-- 其他特色應用 -->
                  <div class="btn-group">
                    <button type="button" class="btn dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">特色應用</button>
                    <div class="dropdown-menu">
                      <a class="dropdown-item" href="{% url 'line_today:movie_home' %}" style="color: blue">LINE Today 熱門電影榜</a>

                      <a class="dropdown-item" href="#">高雄市市長選舉人氣分析</a>
                      <a class="dropdown-item" href="#">珊珊市長人氣</a>
                      <a class="dropdown-item" href="#">阿邁市長人氣</a>
                      <div class="dropdown-divider"></div>
                      <a class="dropdown-item" href="#">疫情發燒監視</a>
                      <a class="dropdown-item" href="#">蘋果發燒站</a>
                      <div class="dropdown-divider"></div>
                      <a class="dropdown-item" href="#">人氣美食排行榜</a>
                      <a class="dropdown-item" href="#">財經議題排行榜</a>
                      <a class="dropdown-item" href="#">股市新聞監視站</a>
                      <a class="dropdown-item" href="#">科技新聞熱門議題分析</a>
                      <a class="dropdown-item" href="#">人力銀行職缺大熱門</a>
                      <div class="dropdown-divider"></div>
                      <a class="dropdown-item" href="#">批踢踢酸民大吐槽</a>
                      <a class="dropdown-item" href="#">批踢踢鄉民來八卦</a>
                      <a class="dropdown-item" href="#">滴卡大學生關心議題</a>
                      <div class="dropdown-divider"></div>
                      <a class="dropdown-item" href="#">新聞媒體政黨傾向調查分析</a>
                      <a class="dropdown-item" href="#">自訂競爭大PK</a>
                    </div>
                  </div>

                  <!-- 會員訂閱 -->
                  <div class="btn-group">
                    <button type="button" class="btn dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">付費訂閱</button>
                    <div class="dropdown-menu">
                      <a class="dropdown-item" href="#">長時間(超過3個月)監測分析(收費表)</a>
                      <a class="dropdown-item" href="#">更多資料庫分析(收費表)</a>
                      <a class="dropdown-item" href="#">為你訂製輿情分析任務(報價)</a>
                    </div>
                  </div>

                  <!-- 關於 -->
                  <div class="btn-group">
                    <button type="button" class="btn dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">關於</button>
                    <div class="dropdown-menu">
                      <a class="dropdown-item" href="#">課程介紹網頁</a>
                      <a class="dropdown-item" href="#">如何使用輿情API</a>
                    </div>
                  </div>
                </ul>
              </div>
            </div>
          </nav>
        </div>

        <!-- End of Navigation Bar -->

        <!-- Main Content -->
        {% block content %}

        {% endblock %}
      </div>
    </div>

    <!-- Bootstrap 5 JS Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <!-- Additional Scripts -->
    {% block extra_js %}

    {% endblock %}
  </body>
</html>